msgboard/config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :edit, :update, :show]

  resources :categories, only: [:index, :new, :create, :show]

  resources :posts do
    resources :comments
  end

end

msgboard/app/models/category.rb
class Category < ActiveRecord::Base
	has_many :connections
	has_many :posts, through: :connections

	validates :title, presence: true
end

msgboard/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user

	validates :content, presence: true
end

msgboard/app/models/connection.rb
class Connection < ActiveRecord::Base
	belongs_to :post
	belongs_to :category
end

msgboard/app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	has_many :connections
	has_many :categories, through: :connections
	belongs_to :user

	validates :title, :content, presence: true
end

msgboard/app/models/user.rb
class User < ActiveRecord::Base
	has_many :comments
	has_many :posts

	validates :name, presence: true, uniqueness: true
	validates :password_digest, presence: true, on: :create, length: {minimum: 5}

	validates :name, length: {minimum: 2}
	validates :name, length: {maximum: 100}

	has_secure_password validations: false
end

msgboard/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :getcategory_all

  def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def getcategory_all
    @getcategory_all = Category.all
  end
end

msgboard/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
    @posts = @category.posts
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to root_path
    else
      flash[:errorcategory] = "Please enter category!"
      redirect_to new_category_path
    end
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end

end

msgboard/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params.require(:comment).permit(:content))

    @comment.user = current_user
    if @comment.save
      redirect_to post_path(@post)
    else
      flash[:errorcomment] = "Please enter your comment!"
      # render 'posts/show'
      redirect_to post_path(@post)
    end

  end
end

msgboard/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    #前端使用者傳回的資料，建立一個新的 post 物件
    post = Post.new(post_params)
    post.user = current_user

    #如果成功存進資料庫，就導回 index 頁面，失敗就再顯示一次表單
    if post.save
      redirect_to posts_path
    else
      flash[:errornewpost] = "Please enter your post's title and content!"
      redirect_to new_post_path
      # render :new
    end
  end

  private

	#確保 params 裡面的 post hash 存在，並且允許 title 和 content 被存取
	def post_params
	  params.require(:post).permit(:title, :content, category_ids: [])
	end
end

msgboard/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:name])

    if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        flash[:successlogin] = "Welcome to #{user.name} message board!"

        redirect_to root_path
    else
      flash[:errorlogin] = "Please chech your name or password!"

      redirect_to login_path
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

msgboard/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:successlogin] = "Welcome to #{@user.name} message board!"
      redirect_to root_path
    else
      flash[:errorregister] = "Please enter your name or password!"
      #binding.pry
      redirect_to register_path
      #render template: "users/new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end
end

msgboard/app/helpers/application_helper.rb
module ApplicationHelper
end

msgboard/app/views/categories/_category.html.erb
<% if category.title == 'Ruby on Rails' %>
  <span class='badge alert-danger'>
<% elsif category.title == 'C#' %>
  <span class='badge alert-success'>
<% elsif category.title == 'Unity' %>
  <span class='badge progress-bar-info'>
<% elsif category.title == 'Javascript' %>
  <span class='badge progress-bar-warning'>
<% elsif category.title == 'Git' %>
  <span class='badge progress-bar-primary'>
<% end %>
  <%= category.title %>
</span>

msgboard/app/views/categories/index.html.erb
<%= render 'shared/title', title: 'All Categories'%>

<div class='row'>
  <div class='well col-md-6'>
    <%= render partial: "categories/category", collection: @categories %>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <%= link_to 'Back to create categooy', new_category_path ,class: 'btn btn-danger'%>
</div>

msgboard/app/views/categories/new.html.erb
<%= render 'shared/title', title: "Create New Category"%>

<div class="well col-md-6">
  <% flash.each do |key, value| %>
    <% if key == "errorcategory"%>
      <div class="alert alert-danger" role="alert" style="color:red"><%= value %></div>
    <% end %>
  <% end %>

  <%= form_for @category do |c| %>
    <div class="form-group">
    	<%= label_tag :category_title %>
      <sup class="required" title="Required" style="color:red">*</sup>
    	<br>
    	<%= c.text_field :title %>
    </div>
    <%= c.submit 'Create Category', class: 'btn btn-primary' %>
    &nbsp;&nbsp;&nbsp;
    <%= link_to 'All Category', categories_path ,class: 'btn btn-info'%>
  <% end %>
</div>

msgboard/app/views/categories/show.html.erb
<%= render 'shared/title', title: "Post >>> #{@category.title}"%>

<% @posts.each do |post| %>
  <div class="row">
    <div class="well col-md-8">
      <%= render partial: "categories/category", collection: post.categories %>
      <p>
        <h3><%= link_to "#{post.title}", post_path(post) %></h3>
      </p>
      <p>
        <%= post.content %>
      </p>
      <br>
    </div>
  </div>
<% end %>

msgboard/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to image_tag("M.png", size: "40x40", :style => "margin-top:-10px; margin-right: -10px;"),  root_path, :class => 'navbar-brand' %>
      <%= link_to image_tag("B.png", size: "40x40", :style => "margin-top:-10px;"),  root_path, :class => 'navbar-brand' , :style => "margin-right:-10px;"%>
    </div>

    <div class="navbar-header">
      <%= link_to "Massage Board",  root_path, :class => 'navbar-brand', :style => "margin-left:1px;"%>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li><%= link_to 'New Post', new_post_path %></li>
          <!-- <li><%= link_to 'New Category', new_category_path %></li> -->
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <%= link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown' do %>
            <%= current_user.name %> <span class='caret'></span>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to 'User Profile', user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Logout', logout_path %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sing up', register_path %></li>
          <li><%= link_to 'Login', login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="navbar navbar-default navbar-fixed-bottom" style="height: 50px">
  <div class="container_nav">
    <div class="navbar-text pull-left">
      <p>© 2016, NTU-ROR-274, HJS's Project. </p>
    </div>
  </div>
</div>

<div class="navbar navbar-inverse rolldown" style="height: 50px">
  <div class="container_rolldown">
    <div class="navbar-text pull-left">
      <h4>
        <% getcategory_all.each do |category| %>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to "#{category.title}", href = "/categories/#{category.id}" %>
        <% end %>
      </h4>
    </div>
  </div>
</div>

msgboard/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Msgboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<%= render 'layouts/navigation' %>
</header>
<div class="container">
  <!-- <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>-->
  <div class="row">
    <div class="col-md-12">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

msgboard/app/views/posts/_post.html.erb
  <div class="row">
    <div class="well col-md-8">
      <%= render partial: "categories/category", collection: post.categories %>
      <p>
        <h3><%= link_to "#{post.title}", post_path(post) %></h3>
      </p>
      <p>
        <%= post.content %>
      </p>
      <br>
      <!-- <span>
        <%= link_to "show this post", post_path(post) %>
      </span> -->
    </div>
  </div>

msgboard/app/views/posts/index.html.erb
<% flash.each do |key, value| %>
  <% if key == "successlogin"%>
    <div class="alert alert-success alert-dismissible" role="alert" style="color:green">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h1><%= value %></h1>
    </div>
  <% end %>
<% end %>

<%= render 'shared/title', title: 'Post List'%>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

msgboard/app/views/posts/new.html.erb
<%= render 'shared/title', title: 'New Post'%>

<div class="well col-md-6">
  <% flash.each do |key, value| %>
    <% if key == "errornewpost"%>
      <div class="alert alert-danger" role="alert" style="color:red"><%= value %></div>
    <% end %>
  <% end %>

  <%= form_for @post do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <sup class="required" title="Required" style="color:red">*</sup>
      <br>
      <%= f.text_field :title, size: "70"%>
    </div>
    <div class="form-group">
      <%= f.label :content %>
      <sup class="required" title="Required" style="color:red">*</sup>
      <br>
      <%= f.text_area :content, size: "70x10" %>
    </div>
    <div class="form-group">
      <%= f.label :categories %>
      <br>
      <%= collection_check_boxes(:post, :category_ids, Category.all, :id, :title) do |cbox|%>
      <%= cbox.label(class: "checkbox-inline") { cbox.check_box(class: "checkbox") + cbox.text } %>
      <% end %>
    </div>
  <br>
    <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary') %>
    &nbsp;&nbsp;&nbsp;
    <%= link_to 'Back to Post List', posts_path ,class: 'btn btn-danger'%>
  <% end %>
</div>

msgboard/app/views/posts/show.html.erb
<% flash.each do |key, value| %>
  <% if key == "errorcomment"%>
    <div class="alert alert-danger alert-dismissible" role="alert" style="color:red">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
    <%= value %>
  </div>
  <% end %>
<% end %>

<%= render 'shared/title', title: "#{@post.title}"%>

<div class="row">
  <div class="col-md-8 well">
    <%= render partial: "categories/category", collection: @post.categories %>
    <h3><%= @post.title %></h3>
    <p>
      <%= @post.content %>
    </p>
    <br>
    <small>posted by </small><%= " #{@post.user.name}" %>
  </div>
</div>

<h4>All Comments:</h4>

<% @post.comments.each do |comment| %>
  <div class="row">
    <div class="well col-md-6">
      <p>
        <%= comment.content %>
      </p>
      <br>
      <small>commented by </small><%= "#{comment.user.name}" %>
    </div>
  </div>
<% end %>

<% if logged_in? %>

  <h4>Leave a comment:</h4>
  <%= form_for [@post, @comment] do |f| %>
    <div class="row">
      <%= f.text_area :content, rows: 3, size: "70x5" %>
      <br>
      <%= f.submit 'Create Comment', class: 'btn btn-primary' %>
      &nbsp;&nbsp;&nbsp;
      <%= link_to 'Go back to all posts', posts_path ,class: 'btn btn-danger'%>
      <p>
    </div>
  <% end %>

<% end %>

msgboard/app/views/shared/_title.html.erb
<h3><%= title %></h3>

msgboard/app/views/users/new.html.erb
<%= render '/shared/title', title: 'Register'%>

<div class="well col-md-6">
  <% flash.each do |key, value| %>
    <% if key == "errorregister"%>
      <div class="alert alert-danger" role="alert" style="color:red"><%= value %></div>
    <% end %>
  <% end %>

  <%= form_for @user do |f| %>
  <div class="form-group">
    <%= label_tag :name %>
    <sup class="required" title="Required" style="color:red">*</sup>
    <br>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= label_tag :password %>
    <sup class="required" title="Required" style="color:red">*</sup>
    <br>
    <%= f.password_field :password%>
  </div>

  <br>
  <%= f.submit(@user.new_record? ? 'Register' : 'Update Profile', class: 'btn btn-primary') %>
  <% end %>
</div>

msgboard/app/views/users/show.html.erb
<%= render 'shared/title', title: "#{@user.name}'s activities"%>

<h4><%= current_user.name %>'s posts:</h4>

<% @user.posts.each do |post| %>

<div class="row">
  <div class="col-md-6 well">
    <h3><%= post.title %></h3>
    <p>
      <%= post.content %>
    </p>
    <br>
    <small>posted by </small><%= " #{post.user.name}" %>
  </div>
</div>

<% end %>
<hr>
<h4><%= current_user.name %>'s comments:</h4>

<% @user.comments.each do |comment| %>
  <div class="row">
    <div class="col-md-6 well">
      <p>
        <%= comment.content %>
      </p>
      <br>
      <small>commented by </small><%= "#{comment.user.name}" %>
    </div>
  </div>
<% end %>

<%= link_to 'Back to Post List', posts_path ,class: 'btn btn-danger'%>
  <br>
  <br>
  <br>